config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  # mount Browserlog::Engine => '/logs'

  resources :vouchers

  resources :downloads do
    collection do
      get :get
    end

    member do
      get :show_recent
    end
  end

  resources :shortcodes do
    member do
      put :toggle_enabled
    end
  end

  resources :money_transactions
  resources :destinations do
    collection do
      get :go
    end

    member do
      get :visits
    end
  end

  resources :help_topics
  resources :help_groups
  resources :help_placements

  resources :feedbacks do
    collection do
      get :list
    end
  end

  resources :error_reports do
    member do
      get :resolution
    end
  end

  resources :users do
    collection do
      get :signup
      post :find_results
      get :list_translation_languages
      post :update_name_and_email
      post :update_translation_language_results
      post :update_display_settings
      get :translation_analytics_welcome
      post :update_password
      get :find
      get :clients
      get :top
      get :my_profile
      get :bilinguals
      get :clients_by_source
      get :translators
      get :request_practice_project
      get :admins
      get :supporters
      post :setup_practice_project
      get :complete_sandbox
      get :remove_compact_display_session
    end

    member do
      post :update_rate
      patch :update_autoassignment
      post :do_verification_deposit
      post :add_from_languages
      get :reset_password
      post :edit_categories
      post :edit_personal_details
      get :validate
      post :invite_to_job
      post :request_external_account_validation
      post :add_to_languages
      get :managed_works
      post :edit_resume
      get :manage_aliases
      post :resend_activation_email
      get :validate_external_account
      post :del_language
      post :update_public
      post :edit_translation_availability
      post :update_tool
      post :edit_affiliate
      post :add_verification_document
      post :add_language_document
      post :toggle_admin_notifications
      post :edit_image
      get :verification
      post :update_tool_others
      post :del_verification_document
      post :del_language_document
      get :resend_confirmation_email
      post :update_bio
      get :manage_works
      get :translator_languages
      post :close_account
      post :edit_language
      post :update_supporter_data
      get :web_messages_list
      post :validate_user_vat
    end

    resources :translators do
      member do
        patch :update_autoassignment
      end
    end

    resources :user_clicks
    resources :vacations

    resources :glossary_terms do
      collection do
        post :csv_export
        post :import
        get :ta_glossary_edit
        get :new_import
        get :new_tmx_import
        post :tmx_import
        post :show_glossary
      end

      member do
        post :edit_translation
        post :locate
      end
    end

    resources :tus do
      collection do
        get :search
      end
    end

    resources :language_managers do
      resources :language_manager_applications do
        member do
          post :update_application_status
          post :create_message
          get :attachment
        end
      end
    end
  end

  resources :bookmarks

  resources :newsletters do
    collection do
      get :feed
      get :sitemap
    end
    member do
      get :plain
      get :count_users
      put :test
    end
  end

  resources :advertisements
  resources :leads do
    collection do
      post :import
    end
  end

  resources :reminders do
    collection do
      get :hide
      get :unhide
      post :delete_selected
    end
  end

  resources :arbitrations do
    collection do
      get :supporter_index
      post :request_cancel_bid
      post :create_cancel_bid_arbitration
      get :pending
      get :summary
    end

    member do
      post :assign_to_supporter
      post :edit_ruling
      post :ask_for_supporter
      post :edit_offer
      post :close
      post :create_message
      post :delete_offer
      post :accept_offer
    end
  end

  resources :projects do
    collection do
      get :lookup_by_private_key
      get :new_sisulizer
      get :searcher
      get :continue_sisulizer
      post :create_sisulizer
      get :summary
    end

    member do
      get :can_create_new_revisions
    end

    resources :support_files

    resources :revisions do
      collection do
        post :lookup_by_private_key
      end

      member do
        post :transfer_payment_for_translation
        post :edit_name
        post :pay_bids_with_paypal
        post :edit_categories
        get :invite_translator
        post :edit_conditions
        post :pay_bids_with_transfer
        get :support_file
        post :edit_languages
        post :add_required_amount_for_auto_accept
        post :reuse_translators
        post :edit_source_language
        get :select_private_translators
        post :edit_file_upload
        post :edit_project_description
        post :review_payment_for_private_translators
        post :edit_description
        post :edit_release_status
        post :update_supporter_data
        get :support_files
      end

      resources :versions do
        member do
          post :duplicate_complete
        end
      end

      resources :chats do
        collection do
          post :send_broadcast
        end

        member do
          post :check_invoice_status
          post :delete_bid
          post :finalize_review
          post :transfer_bid_payment
          post :reopen
          post :refuse_bid
          post :enable_review
          post :finalize_bids
          post :cancel_bid
          post :pay_for_review
          put :update_bid
          post :declare_done
          post :create_message
          post :cancel_review
          post :edit_bid
          post :open_bid_to_edit
          post :accept_bid
          get :attachment
          post :set_access
          post :save_bid
          post :review_complete
          post :finalize_bid
        end

        resources :bids do
          collection do
            post :unset_all_bids
          end

          member do
            post :unset_bid
          end
        end
      end
    end
  end

  resources :websites do
    collection do
      post :ts_quote
      get :new_user
      get :cms_requests
      get :searcher
      get :translators
      post :create_by_cms
      get :validate_affiliate
    end

    member do
      get :search_cms
      get :request_transfer_account
      get :custom_text
      post :close_all
      post :transfer_account
      get :flush_requests
      get :explain
      get :create_language_pair
      get :quote
      post :add_counts
      get :web_messages_for_pickup
      post :reuse_translators
      get :get
      post :create_explanation
      post :store
      get :translator_chat
      post :swap_translators
      post :ack_message_pickup
      post :create_message
      get :new_ticket
      get :language_pair
      post :edit_tm_use
      post :update_by_cms
      post :migrate
      post :edit_description
      post :update_supporter_data
      post :create_ticket
      get :links
      post :confirm_resignation
      post :confirmed_resignation
      get :cancel_resignation
      post :reveal_wp_credentials
      get :all_comm_errors
    end

    resources :shortcodes do
      member do
        put :toggle_enabled
      end
    end

    resources :translation_snapshots do
      collection do
        post :create_by_cms
      end
    end

    resources :website_translation_offers do
      collection do
        get :enter_password
        get :load_or_create_from_ta
      end

      member do
        get :review
        get :report
        post :cancel_invitations
        get :enter_details
        post :update_details
        post :resend_notifications
        post :update_site_status
        get :new_invitation
        get :auto_setup
        post :edit_description
        post :create_invitation
        get :resign_from_website
      end

      resources :website_translation_contracts do
        member do
          post :update_application_status
          post :create_message
          get :attachment
        end
      end
    end

    match '/websites/:website_id/website_translation_contracts/send_broadcast' => 'website_translation_contracts#send_broadcast', :as => :website_translation_contracts_broadcast, via: [:post]

    resources :cms_requests do
      collection do
        get :report
        get :count_requests_to_pickup
        get :cms_id
        post :update_cms_id
        post :multiple_retry
        post :cancel_multiple_translations
      end

      member do
        post :retry
        get :cms_upload
        get :get_html_output
        post :notify_tas_done
        post :store_output
        post :enable_review
        post :report_error
        post :close_all_errors
        get :chat
        post :reset
        get :cms_download
        post :cancel_translation
        post :resend
        post :redo
        post :update_status
        post :debug_complete
        post :create_message
        get :xliff
        post :update_permlink
        post :release
        post :deliver
        post :assign_to_me
        post :notify_cms_delivery
        get :download
        post :update_languages
        post :toggle_tmt_config
        post :toggle_force_ta
      end

      resources :comm_errors
    end

    resources :cms_terms do
      resources :cms_term_translations
    end
  end

  match 'wpml-websites/:id.:format' => 'websites#show', :via => :get

  resources :web_messages do
    collection do
      get :review_index
      get :searcher
      get :fetch_next
      post :pre_create
      post :select_to_languages
    end

    member do
      get :review
      get :translation

app/helpers/admin_finance_helper.rb
module AdminFinanceHelper
  def account_description(account)
    if (account.class == UserAccount) && account.normal_user
      link_to("%s's account" % account.normal_user.try(:full_name), controller: :finance, action: :account_history, id: account.id)
    elsif account.class == BidAccount
      bid = account.bid
      link_to('bid', controller: :bids, action: :show, id: bid.id, chat_id: bid.chat_id, revision_id: bid.chat.revision_id, project_id: bid.chat.revision.project_id)
    elsif account.class == ExternalAccount
      "#{ExternalAccount::NAME[account.external_account_type]} account: #{account.identifier}"
    else
      'some account'
    end
  end

  def money_transaction_details(_account_line, money_transaction)
    "From #{account_description(money_transaction.source_account)} to #{account_description(money_transaction.target_account)}"
  end

  def amount_with_sign(money_transaction)
    if money_transaction.source_account.class == ExternalAccount
      money_transaction.amount
    else
      -money_transaction.amount
    end
  end

  def display_paypal_transactions(all_events, user)
    content_tag(:tbody) do
      keys = all_events.keys().sort
      keys.each do |key|
        entry = all_events[key]
        if entry.class == Invoice
          date = entry.modify_time
          description = content_tag(:span) {
            concat  'Invoice '.html_safe
            concat content_tag(:span, entry.id); concat ' :<br />'.html_safe
            concat content_tag(:ul, style: 'padding: 0') {
              concat content_tag(:li, content_tag(:span, entry.description(user)), style: 'list-style-type: none')
            }
          }
          net_amount = entry.net_amount
          gross_amount = entry.gross_amount
          col = '#E0FFE0'
        else
          total = 0
          fees = 0
          descriptions = []
          entry.mass_payment_receipts.each do |mass_payment_receipt|
            money_transaction = mass_payment_receipt.money_transaction
            total += money_transaction.amount if money_transaction.present?
            fees += mass_payment_receipt.fee
            sa = money_transaction.source_account if money_transaction.present?
            name = sa.present? ? "#{sa.normal_user.try(:full_name)} #{sa.normal_user.try(:type)}" : 'Unknown'
            descriptions << "withdrawal from user account: #{name}"
          end
          date = entry.submit_time
          description = content_tag(:span) {
            concat  'MassPay '.html_safe
            concat content_tag(:span, entry.id); concat ' :<br />'.html_safe
            concat content_tag(:ul, style: 'padding: 0') {
              descriptions.each do |desc|
                concat content_tag(:li, desc, style: 'list-style-type: none')
              end
            }
          }
          net_amount = -total
          gross_amount = -(total + fees)
          col = '#FFE0E0'
        end
        concat content_tag(:tr) {
          concat content_tag(:td, disp_date(date), style: "background-color: #{col}")
          concat content_tag(:td, description, style: "background-color: #{col}")
          concat content_tag(:td, net_amount, style: "background-color: #{col}")
          concat content_tag(:td, gross_amount, style: "background-color: #{col}")
        }
      end
    end
  end

end

app/views/admin_finance/_account_line.html.erb
<% if account_line.money_transaction %>
<tr>
	<td><%= disp_time(account_line.chgtime) %></td>
	<td><%= money_transaction_details(account_line, account_line.money_transaction) %></td>
	<td class="moneycolumn"><%= account_line.money_transaction.amount %></td>
	<td class="moneycolumn"><%= account_line.money_transaction.fee %></td>
	<td class="moneycolumn"><%= account_line.balance %></td>
</tr>
<%end%>

app/views/admin_finance/_country.html.erb
<tr>
  <td><%= country.name %></td>
  <td><%= country.tax_group %></td>
  <td><%= country.tax_name %></td>
  <td><%= country.tax_rate %></td>
</tr>

app/views/admin_finance/_money_transaction.html.erb
<tr>
<td><%= money_transaction.id %></td>
<td><%= disp_time(money_transaction.chgtime) %></td>
<td><%= account_description(money_transaction.source_account) %></td>
<td><%= account_description(money_transaction.target_account) %></td>
<td><%= money_transaction.operation_code %></td>
<td><%= amount_with_sign(money_transaction) %></td>
</tr>

app/views/admin_finance/_receipt.html.erb
<!-- Date','ID','Withdrawal ID','TXN','Fee', 'Status' -->
<tr>
	<td><%= disp_time(receipt.chgtime) %></td>
	<td><%= link_to("Mass payment #{receipt.withdrawal_id}", {:action=>:payment, :id=>receipt.id}) %></td>
	<td><%= receipt.id %></td>
	<td><%= receipt.txn %></td>
	<td><%= receipt.fee %></td>
	<td><%= MassPaymentReceipt::TRANSFER_STATUS_TEXT[receipt.status] %></td>
	
</tr>

app/views/admin_finance/countries_taxes.html.erb
View:
  <%= link_to 'EU', {:group => 'EU'} %>
  <%= link_to 'All' %>

<br/>
<%= infotab_header(['Country', 'Tax Group', 'Tax Name', 'Tax Rate']) %>
  <%= render(:partial=>'country', :collection=>@countries) %>
</table>

app/views/admin_finance/external_transactions.html.erb
<% if @list_of_pages %>
  <div class="pager_control">
    Showing page
    <%= form_tag({:action=>:external_transactions}, {:method=>'GET'}) %>
      <span><%= select_tag( :page, options_for_select(@list_of_pages,@transactions.number), {:onchange=>"submit()"}) %> <%= link_to("Prev", url_for(:action=>:external_transactions, :page=>@transactions.prev.number)) if @transactions.prev? %> <%= link_to("Next", url_for(:action=>:external_transactions, :page=>@transactions.next.number)) if @transactions.next? %></span>
    </form>
  </div>
<% end %>

<%= infotab_header(['ID', 'Time', 'From', 'To', 'Description', 'Amount']) %>

<% @transactions.each do |money_transaction| %>
  <%= render(:partial=>'money_transaction', locals: {money_transaction: money_transaction} ) %>
<% end %>

</table>

app/views/admin_finance/history.html.erb
<% if @list_of_pages %>
<div class="pager_control">
	Showing page <%= form_tag({:action=>:history}, {:method=>'GET'}) %>
		<%= select_tag( :page, options_for_select(@list_of_pages,@account_lines.number), {:onchange=>"submit()"}) %>
    &nbsp;<%= (link_to("Prev", url_for(:action=>:history, :page=>@account_lines.prev.number))) if @account_lines.prev? %>
    &nbsp;<%= (link_to("Next", url_for(:action=>:history, :page=>@account_lines.next.number))) if @account_lines.next? %>
</form>
</div>
<% end %>

  <%= infotab_header(['Date','Transaction','Amount','Fee','Balance'], {'Amount' => {'class'=>'moneycolumn'}, 'Fee' => {'class'=>'moneycolumn'}, 'Balance' => {'class'=>'moneycolumn'}}) %>

  <% @account_lines.each do |account_line| %>
    <%= render partial: 'account_line', locals: { account_line: account_line } %>
  <% end %>

</table>

app/views/admin_finance/index.html.erb
<h2>Money summary in the system</h2>

<%= form_tag("/admin_finance", method: :get) do %>
    <div style="float:right;">
    <b>Select Date</b> <%= date_picker_field "d", nil, {value:  params[:d].to_s.to_date}, '<i class="mc-icon-calendar"></i>' %>
    <%= submit_tag 'Filter', data: { disable_with: 'Please wait' } %>
    | <%= link_to 'Reset', {controller: 'admin_finance', action: 'index'} %>
    </div>
<% end %>
<br style="clear:both;">
<br>
<%= infotab_header(['Users balance','Bids balance','Fees balance','Total']) %>
	<tr>
		<td class="moneycolumn"><%= number_to_currency(@user_total, precision: 2) %></td>
		<td class="moneycolumn"><%= number_to_currency(@bids_total, precision: 2) %></td>
		<td class="moneycolumn"><%= number_to_currency(@fees_total, precision: 2) %></td>
		<td class="moneycolumn"><%= number_to_currency(@total, precision: 2) %></td>
	</tr>
</table>

app/views/admin_finance/invoice_search.html.erb
<%= form_tag({:controller=>:finance, :action=>:invoice}, :method=>'GET' ) do %>
	<p>Invoice ID: <%= id_field_tag(:id, '') %></p>
	<p><%= submit_tag('Search', data: { disable_with: 'Search' }) %></p>
<% end %>

app/views/admin_finance/payments.html.erb
<% if @receipts && (@receipts.length > 0) %>
	<%= infotab_header(['Date','Withdrawal', 'Payment ID','TXN','Fee', 'Status']) %>
	<%= render(:partial=>'receipt', :collection=>@receipts) %>
	</table>
<% else %>
	<p>No mass payments to show.</p>
<% end %>

app/views/admin_finance/paypal_transactions.html.erb
<div class="infobox"><h4>Date range</h4>
<%= form_tag({:action=>:paypal_transactions}, :method=>:get) do %>
<table>
	<tr><td>Start date:</td><td><%= select_date(@start_date, {:prefix=>'start_date'}) %></td></tr>
	<tr><td>End date:</td><td><%= select_date(@end_date, {:prefix=>'end_date'}) %></td></tr>
</table>
<br /><p><%= submit_tag('Update display', data: { disable_with: 'Update display' }) %></p>
<p><%= link_to('All dates', {:action=>:paypal_transactions}) %></p>
<% end %>
</div>
<br /><br />

<%= infotab_header(['Date','Description','Net Amount','Gross Amount']) %>
<%= display_paypal_transactions(@all_events,@user) %>
</table>

<br /><p><%= link_to('CSV version', csv_url() ) %></p>

app/views/admin_finance/revenue_report.erb
<%= form_tag("/admin_finance/revenue_report", :method => :get) do %>
    From <%= date_picker_field "from", nil, {:value =>  params[:from].to_s.to_date || Date.today - 1.month}, '<i class="mc-icon-calendar"></i>' %>
    To <%= date_picker_field "to", nil, {:value => params[:to].to_s.to_date || Date.today}, '<i class="mc-icon-calendar"></i>' %>
    <%= submit_tag 'Generate', data: { disable_with: 'Please wait' } %>
  <% end %>

<%= infotab_top(_('Revenue Report'), _('Detailed revenue per project kind.')) %>
<%= infotab_header(['','Software Projects', 'Bidding Projects', 'CMS Projects','Instant Translation Projects', 'Total Amount']) %>

  <tr>
    <th>Totals</th>  
    <td><%= @results[:software] %></td>  
    <td><%= @results[:bidding] %></td>  
    <td><%= @results[:cms] %></td>  
    <td><%= @results[:instant_translation] %></td>  
    <td><%= @results.values.inject :+ %></td>  
    
  </tr>
</table>