config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  # mount Browserlog::Engine => '/logs'

  resources :vouchers

  resources :downloads do
    collection do
      get :get
    end

    member do
      get :show_recent
    end
  end

  resources :shortcodes do
    member do
      put :toggle_enabled
    end
  end

  resources :money_transactions
  resources :destinations do
    collection do
      get :go
    end

    member do
      get :visits
    end
  end

  resources :help_topics
  resources :help_groups
  resources :help_placements

  resources :feedbacks do
    collection do
      get :list
    end
  end

  resources :error_reports do
    member do
      get :resolution
    end
  end

  resources :users do
    collection do
      get :signup
      post :find_results
      get :list_translation_languages
      post :update_name_and_email
      post :update_translation_language_results
      post :update_display_settings
      get :translation_analytics_welcome
      post :update_password
      get :find
      get :clients
      get :top
      get :my_profile
      get :bilinguals
      get :clients_by_source
      get :translators
      get :request_practice_project
      get :admins
      get :supporters
      post :setup_practice_project
      get :complete_sandbox
      get :remove_compact_display_session
    end

    member do
      post :update_rate
      patch :update_autoassignment
      post :do_verification_deposit
      post :add_from_languages
      get :reset_password
      post :edit_categories
      post :edit_personal_details
      get :validate
      post :invite_to_job
      post :request_external_account_validation
      post :add_to_languages
      get :managed_works
      post :edit_resume
      get :manage_aliases
      post :resend_activation_email
      get :validate_external_account
      post :del_language
      post :update_public
      post :edit_translation_availability
      post :update_tool
      post :edit_affiliate
      post :add_verification_document
      post :add_language_document
      post :toggle_admin_notifications
      post :edit_image
      get :verification
      post :update_tool_others
      post :del_verification_document
      post :del_language_document
      get :resend_confirmation_email
      post :update_bio
      get :manage_works
      get :translator_languages
      post :close_account
      post :edit_language
      post :update_supporter_data
      get :web_messages_list
      post :validate_user_vat
    end

    resources :translators do
      member do
        patch :update_autoassignment
      end
    end

    resources :user_clicks
    resources :vacations

    resources :glossary_terms do
      collection do
        post :csv_export
        post :import
        get :ta_glossary_edit
        get :new_import
        get :new_tmx_import
        post :tmx_import
        post :show_glossary
      end

      member do
        post :edit_translation
        post :locate
      end
    end

    resources :tus do
      collection do
        get :search
      end
    end

    resources :language_managers do
      resources :language_manager_applications do
        member do
          post :update_application_status
          post :create_message
          get :attachment
        end
      end
    end
  end

  resources :bookmarks

  resources :newsletters do
    collection do
      get :feed
      get :sitemap
    end
    member do
      get :plain
      get :count_users
      put :test
    end
  end

  resources :advertisements
  resources :leads do
    collection do
      post :import
    end
  end

  resources :reminders do
    collection do
      get :hide
      get :unhide
      post :delete_selected
    end
  end

  resources :arbitrations do
    collection do
      get :supporter_index
      post :request_cancel_bid
      post :create_cancel_bid_arbitration
      get :pending
      get :summary
    end

    member do
      post :assign_to_supporter
      post :edit_ruling
      post :ask_for_supporter
      post :edit_offer
      post :close
      post :create_message
      post :delete_offer
      post :accept_offer
    end
  end

  resources :projects do
    collection do
      get :lookup_by_private_key
      get :new_sisulizer
      get :searcher
      get :continue_sisulizer
      post :create_sisulizer
      get :summary
    end

    member do
      get :can_create_new_revisions
    end

    resources :support_files

    resources :revisions do
      collection do
        post :lookup_by_private_key
      end

      member do
        post :transfer_payment_for_translation
        post :edit_name
        post :pay_bids_with_paypal
        post :edit_categories
        get :invite_translator
        post :edit_conditions
        post :pay_bids_with_transfer
        get :support_file
        post :edit_languages
        post :add_required_amount_for_auto_accept
        post :reuse_translators
        post :edit_source_language
        get :select_private_translators
        post :edit_file_upload
        post :edit_project_description
        post :review_payment_for_private_translators
        post :edit_description
        post :edit_release_status
        post :update_supporter_data
        get :support_files
      end

      resources :versions do
        member do
          post :duplicate_complete
        end
      end

      resources :chats do
        collection do
          post :send_broadcast
        end

        member do
          post :check_invoice_status
          post :delete_bid
          post :finalize_review
          post :transfer_bid_payment
          post :reopen
          post :refuse_bid
          post :enable_review
          post :finalize_bids
          post :cancel_bid
          post :pay_for_review
          put :update_bid
          post :declare_done
          post :create_message
          post :cancel_review
          post :edit_bid
          post :open_bid_to_edit
          post :accept_bid
          get :attachment
          post :set_access
          post :save_bid
          post :review_complete
          post :finalize_bid
        end

        resources :bids do
          collection do
            post :unset_all_bids
          end

          member do
            post :unset_bid
          end
        end
      end
    end
  end

  resources :websites do
    collection do
      post :ts_quote
      get :new_user
      get :cms_requests
      get :searcher
      get :translators
      post :create_by_cms
      get :validate_affiliate
    end

    member do
      get :search_cms
      get :request_transfer_account
      get :custom_text
      post :close_all
      post :transfer_account
      get :flush_requests
      get :explain
      get :create_language_pair
      get :quote
      post :add_counts
      get :web_messages_for_pickup
      post :reuse_translators
      get :get
      post :create_explanation
      post :store
      get :translator_chat
      post :swap_translators
      post :ack_message_pickup
      post :create_message
      get :new_ticket
      get :language_pair
      post :edit_tm_use
      post :update_by_cms
      post :migrate
      post :edit_description
      post :update_supporter_data
      post :create_ticket
      get :links
      post :confirm_resignation
      post :confirmed_resignation
      get :cancel_resignation
      post :reveal_wp_credentials
      get :all_comm_errors
    end

    resources :shortcodes do
      member do
        put :toggle_enabled
      end
    end

    resources :translation_snapshots do
      collection do
        post :create_by_cms
      end
    end

    resources :website_translation_offers do
      collection do
        get :enter_password
        get :load_or_create_from_ta
      end

      member do
        get :review
        get :report
        post :cancel_invitations
        get :enter_details
        post :update_details
        post :resend_notifications
        post :update_site_status
        get :new_invitation
        get :auto_setup
        post :edit_description
        post :create_invitation
        get :resign_from_website
      end

      resources :website_translation_contracts do
        member do
          post :update_application_status
          post :create_message
          get :attachment
        end
      end
    end

    match '/websites/:website_id/website_translation_contracts/send_broadcast' => 'website_translation_contracts#send_broadcast', :as => :website_translation_contracts_broadcast, via: [:post]

    resources :cms_requests do
      collection do
        get :report
        get :count_requests_to_pickup
        get :cms_id
        post :update_cms_id
        post :multiple_retry
        post :cancel_multiple_translations
      end

      member do
        post :retry
        get :cms_upload
        get :get_html_output
        post :notify_tas_done
        post :store_output
        post :enable_review
        post :report_error
        post :close_all_errors
        get :chat
        post :reset
        get :cms_download
        post :cancel_translation
        post :resend
        post :redo
        post :update_status
        post :debug_complete
        post :create_message
        get :xliff
        post :update_permlink
        post :release
        post :deliver
        post :assign_to_me
        post :notify_cms_delivery
        get :download
        post :update_languages
        post :toggle_tmt_config
        post :toggle_force_ta
      end

      resources :comm_errors
    end

    resources :cms_terms do
      resources :cms_term_translations
    end
  end

  match 'wpml-websites/:id.:format' => 'websites#show', :via => :get

  resources :web_messages do
    collection do
      get :review_index
      get :searcher
      get :fetch_next
      post :pre_create
      post :select_to_languages
    end

    member do
      get :review
      get :translation

app/models/supporter.rb
class Supporter < NormalUser
  has_many :arbitrations
  has_many :error_reports
  has_many :support_tickets
  has_many :contacts

  def users_to_switch
    Client.all + Translator.all
  end

  def email
    if on_vacation?
      'hello@icanlocalize.com'
    else
      self['email']
    end
  end

  def can_view?(_p)
    true
  end

  def can_edit?(_p)
    true
  end

  def can_modify?(_p)
    true
  end

  def can_deposit?
    false
  end

  def can_pay?
    true
  end

  def can_view_finance?
    true
  end

  def verified?
    true
  end

  def self.new_account(name, email, password)
    s = Supporter.new
    s.type = 'Admin'
    s.userstatus = 1
    s.fname = name
    s.lname = 'Supporter'
    s.email = email
    s.nickname = "#{name}.supporter"
    s.password = password
    s.save!
  end
end

app/helpers/supporter_helper.rb
module SupporterHelper
  def cms_clients_table(clients)
    res = infotab_header(%w(Client Projects Kind Jobs))
    client_keys = clients.keys.sort.reverse
    client_keys.each do |client|
      websites = clients[client]
      website_count = websites.length
      if website_count > 10
        have_more_projects = true
        website_count = 10
      else
        have_more_projects = false
      end
      first_project = true
      res += "<tr><td rowspan=\"#{website_count}\">#{user_link(client[1])}"
      if have_more_projects
        res += "<br /><p><b>This client has #{websites.length} projects</b></p>"
      end
      res += '</td>'
      websites[0...website_count].each do |website|
        res += '<tr>' unless first_project
        res += '<td>' + link_to(website.name, controller: '/wpml/websites', action: :show, id: website.id) + '</td>'
        res += "<td>#{WEBSITE_DESCRIPTION[website.cms_kind]}: <b>#{Website::PROJECT_KIND_TEXT[website.project_kind]}</b></td><td>#{website.cms_requests.count}</td>"
        res += '</tr>'
        first_project = false
      end
    end
    res += '</table>'
    res
  end

  def background_for_paying_user(user)
    paying = false
    user.money_accounts.each do |money_account|
      paying = true unless money_account.credits.empty?
    end
    paying ? ' style="background-color: #FFE0E0;"' : ''
  end

  def project_and_client_name
    res = '<div class="subframe">' + form_tag(action: :apply_search_filter)
    res += 'Project name: ' + text_field_tag(:project_name, @project_name, size: 20) + ' &nbsp; Client name: ' + text_field_tag(:client_name, @client_name, size: 20)
    res += ' &nbsp; Category: ' + select_tag(:category_id, options_for_select(Category.list, @category_id))
    res += ' &nbsp; ' + submit_tag('Search', data: { disable_with: 'Processing...' })
    res += hidden_field_tag(:continue_to, action_name)
    res += '</form>'
    if !@project_name.blank? || !@client_name.blank? || !@category_id.blank?
      res += ' &nbsp; ' + button_to('Clear search', action: :apply_search_filter, continue_to: action_name)
    end

    res += '</div>'
    res.html_safe
  end

  def translator_auto_assign_button(translator, assigned_translators_ids)
    auto_assign_button(translator, assigned_translators_ids, 'translator')
  end

  def reviewer_auto_assign_button(translator, assigned_reviewers_ids, review_enabled)
    return content_tag(:span, 'Review Disabled') unless review_enabled
    return content_tag(:span, "Level #{translator[:level]} Translator") unless translator[:level] == 2
    auto_assign_button(translator, assigned_reviewers_ids, 'reviewer')
  end

  def auto_assign_button(translator, assigned_ids, type)
    link = url_for controller: '/supporter', action: :assign_assignment_type, id: translator[:id], assignment_type: type
    exists = assigned_ids.include? translator[:id]
    link_to "Assign as #{type}", link,
            class: "btn btn-xs #{get_auto_assign_button_class(exists)} #{type} #{exists ? 'disabled' : ''}", remote: true
  end

  private

  def get_auto_assign_button_class(exists = false)
    exists ? 'btn-success' : 'btn-default'
  end

end

app/views/supporter/_issue.html.erb
<tr>
	<td><%= issue_title(issue) %></td>
	<td><%= Issue::KIND_TEXT[issue.kind] %></td>
	<td><%= user_link(issue.initiator) %></td>
	<td><%= user_link(issue.target) %></td>
	<td><%= disp_date(issue.created_at) %></td>
	<td><%= disp_date(issue.updated_at) %></td>
</tr>

app/views/supporter/_text_resource.html.erb
<tr>
	<td><%= link_to(text_resource.name, {:controller=>:text_resources, :action=>:show, :id=>text_resource.id}) %></td>
	<td><%= text_resource.category ? text_resource.category.name : '<span class="comment">Not specified</span>'.html_safe %></td>
	<td><%= disp_date(text_resource.created_at) %></td>
	<td <%= background_for_paying_user(text_resource.client).html_safe %>><%= user_link(text_resource.client) %></td>
	<td><% if text_resource.resource_languages.length > 0 %>
		<ul>
      <% text_resource.resource_languages.each do |rl| %>
        <%= content_tag(:li, "#{text_resource.language.name} to #{rl.language.name}") %>
      <% end %>
    </ul>
		<% end %>
	</td>
	<td><%= text_resource.resource_strings.count%></td>
</tr>	
	

app/views/supporter/_web_supports.html.erb
<%= infotab_header(['Name','Client','Statistics']) %>
<%= render(:partial=>'web_support', :collection=>web_supports) %>
</table>

app/views/supporter/_website.html.erb
<tr>
	<td <%= (website.flag != 0) ? ' style="background-color: #FFE0E0;"' : '' %>><%= link_to(website.name, {controller: '/wpml/websites', :action=>:show, :id=>website.id}) %></td>
	<td><%= website.category ? website.category.name : '<span class="comment">Not specified</span>'.html_safe %></td>
	<td><%= disp_date(website.created_at) %></td>
	<td><%= "%s - %s"%[CMS_DESCRIPTION[website.cms_kind],Website::PROJECT_KIND_TEXT[website.project_kind]] %></td>
	<td <%= background_for_paying_user(website.client) %>><%= user_link(website.client) %></td>
	<td><% if website.website_translation_offers.length > 0 %>
		<ul>
      <% website.website_translation_offers.each do |offer| %>
        <li>
          <%= link_to({:controller => :website_translation_offers, :action => :show, :website_id => website.id, :id => offer.id}) do %>
            <span><%= offer.from_language.name %> to <%= offer.to_language.name %> (applications: <%= offer.website_translation_contracts.count %> <b>accepted: <%= offer.accepted_website_translation_contracts.count %></b>)</span>
          <% end %>
        </li>
      <% end %>
    </ul>
		<% end %>
	</td>
	<td><%= website.cms_requests.length %></td>
	<td><%= website.word_count %></td>
	<td><p><%= pre_format(website.note) %></p></td>
</tr>

app/views/supporter/_website_project_auto_assign_modal.html.erb
<div id="translatorList" class="modal fade medium-modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-header">
      <h4><%= title %></h4>
    </div>
    <div class="modal-body">
      <%= form_tag({:controller => '/supporter', :action => :assign_translators_to_language_pair}, method: :post, remote: true) do %>
          <input type="hidden" name="website_translation_offer_id"/>
          <div class="details">
          </div>
          <div id="tableActions" style="display: none" class="pull-right m-b-10">
            <button data-dismiss="modal">Cancel</button>
            <button type="submit">Save</button>
          </div>
          <div class="clearfix"></div>
          <table id="translatorListTable" class="stats" width="100%">
            <tbody>
            <tr class="headerrow">
              <th><%= _('Name') %></th>
              <th colspan="2"><%= _('Action') %></th>
            </tr>
            </tbody>
          </table>
      <% end %>
    </div>
  </div>
</div>

app/views/supporter/_website_translation_offer.html.erb
<tr>
	<td><%= disp_date(website_translation_offer.created_at) %></td>
	<td><%= link_to(website_translation_offer.website.name, {:controller=>:website_translation_offers, :action=>:show, :website_id=>website_translation_offer.website.id, :id=>website_translation_offer.id}) %></td>
	<td><%= website_translation_offer.from_language.name %> -> <%= website_translation_offer.to_language.name %></td>
	<td><%= link_to_if(!website_translation_offer.website.url.blank?, website_translation_offer.website.url, website_translation_offer.website.url, :target=>'_blank') %></td>
	<td><%= CMS_DESCRIPTION[website_translation_offer.website.cms_kind] %></td>
	<td<%= background_for_paying_user(website_translation_offer.website.client) %>><%= user_link(website_translation_offer.website.client) %> - <%= User::USER_STATUS_TEXT[website_translation_offer.website.client.userstatus] %></td>
	<td><%= website_translation_offer.status_summary(@user) %></td>
</tr>

app/views/supporter/cms_projects.html.erb
<% if @flagged_websites.length > 0 %>
<h2>Flagged projects</h2>
<%= infotab_header(['Project','Category','Created','Kind','Client','Languages','Documents sent','Word count','Notes']) %>
<%= render(:partial=>'website', :collection=>@flagged_websites) %>
</table>
<div class="inter_tab_spacer"></div>

<h2>Normal projects</h2>
<% end %>

<%= project_and_client_name() %>
<div class="pager_control">
		Showing page <%= form_tag({:action=>:cms_projects}, {:method=>'GET'}) %>
			<%= select_tag( :page, options_for_select(@list_of_pages,@websites.number), {:onchange=>"submit()"}) %>
		<%= link_to("Prev", url_for(:action=>:cms_projects, :page => @websites.prev.number, :status=>@current_project_status, :prev_status=>@current_project_status)) if @websites.prev? %>
		<%= link_to("Next", url_for(:action=>:cms_projects, :page => @websites.next.number, :status=>@current_project_status, :prev_status=>@current_project_status)) if @websites.next? %>	
	</form>
</div>
	
<%= infotab_header(['Project','Category','Created','Kind','Client','Languages','Documents sent','Word count','Notes']) %>
<% @websites.each do |web| %>
  <%= render(:partial=>'website', locals: {website: web}) %>
<% end %>
</table>
<div class="pager_control">
		Showing page <%= form_tag({:action=>:cms_projects}, {:method=>'GET'}) %>
			<%= select_tag( :page, options_for_select(@list_of_pages,@websites.number), {:id=>'page1', :onchange=>"submit()"}) %>
		<%= link_to("Prev", url_for(:action=>:cms_projects, :page => @websites.prev.number, :status=>@current_project_status, :prev_status=>@current_project_status)) if @websites.prev? %>
		<%= link_to("Next", url_for(:action=>:cms_projects, :page => @websites.next.number, :status=>@current_project_status, :prev_status=>@current_project_status)) if @websites.next? %>	
	</form>
</div>

app/views/supporter/index.html.erb
<h2>Things to do</h2>
<% if @todo_things.length > 0 %>
	<%= infotab_header(['Category', 'todo']) %>
	<% for todo_item in @todo_things %>
		<tr><td><%= todo_item[0] %></td><td><%= link_to(todo_item[1], todo_item[2]) %></td></tr>
	<% end %>
	</table>
<% else %>
	<p>You have no pending tasks.</p>
<% end %>

<h2>My configurations</h2>
<ul>
  <li><%= link_to 'vacations', user_vacations_path(@user) %></li>
</ul>

app/views/supporter/manage_website_project_auto_assign.html.erb
<%
  table_headers = [_('ID'),
                   _('Website'),
                   _('Language Pair'),
  ]
%>
<%= infotab_header(table_headers, {}, 100, 'id="pair_languages"') %>
<% if @translation_offers.present? %>
    <% @translation_offers.each do |trans_offer| %>
        <tr>
          <td><%= trans_offer.id %></td>
          <td><%= link_to trans_offer.website_name, {controller: '/wpml/websites', action: :show, id: trans_offer.website_id}, target: '_blank' %></td>
          <td>
            <% link = url_for action: :assignable_translators_to_website_translation_offers, id: trans_offer.id %>
            <%= link_to "#{trans_offer.source_language_name} &raquo; #{trans_offer.target_language_name}".html_safe, link, remote: true %>
          </td>
        </tr>
    <% end %>
<% else %>
    <tr><td colspan="4">No translation project yet.</td></tr>
<% end %>
</table>


<%= render partial: 'website_project_auto_assign_modal', locals: { title: 'Assign Translators' } %>

app/views/supporter/tasks.html.erb
<div class="content">
	<ol>
		<% for task in @tasks %>
			<li><%= link_to_if(task[2], task[0], task[1]) %></li>
		<% end %>
	</ol>
</div>

app/views/supporter/unfinished_translation_jobs.html.erb
<h1 id="mainheading">Unfinished Translation Jobs</h1>

<div class="pager_control">
  Showing page <%= form_tag({action: :unfinished_translation_jobs}, {method: 'GET'}) %>
  <%= select_tag( :page, options_for_select(@list_of_pages, @cms_requests.number), {onchange: "submit()"}) %>
  <%= link_to("Prev", url_for(action: :unfinished_translation_jobs, page: @cms_requests.prev.number)) if @cms_requests.prev? %>
  <%= link_to("Next", url_for(action: :unfinished_translation_jobs, page: @cms_requests.next.number)) if @cms_requests.next? %>
  </form>
</div>
<table width="100%" cellspacing="0" cellpadding="3" class="stats">
  <tbody>
    <tr class="headerrow">
      <th>Job ID</th>
      <th>Translator</th>
      <th>Translation Status</th>
      <th>% of deadline elapsed</th>
      <th>Time remaining<br>before deadline</th>
    </tr>
    <% @cms_requests.each do |cms_request| %>
      <tr>
        <td>
          <%= link_to(cms_request.id, {controller: 'cms_requests', action: 'show', website_id: cms_request.website_id, id: cms_request.id}, target: '_blank') %>
        </td>
        <td>
          <% if cms_request.cms_target_language.translator %>
            <%= link_to(cms_request.cms_target_language.translator.nickname, user_path(cms_request.cms_target_language.translator), target: '_blank') %> | <%= link_to_translator_chat(cms_request.cms_target_language) %>
          <% elsif cms_request.website_translation_offer.accepted_website_translation_contracts.any? %>
            <%= accepted_translator_names_and_chat_links(cms_request.website_translation_offer) %>
          <% else %>
            No translator assigned
          <% end %>
        </td>
        <td><%= CmsTargetLanguage::STATUS_TEXT[cms_request.cms_target_language.status] %></td>
        <td>
          <% if cms_request.deadline_elapsed_percentage > 100 %>
            Already overdue
          <% else %>
              <%= number_to_percentage(cms_request.deadline_elapsed_percentage, strip_insignificant_zeros: true, precision: 2 ) %>
          <% end %>
        </td>
        <td>
          <% if cms_request.deadline >= Time.now %>
              <%= seconds_to_pretty_time(cms_request.deadline - Time.now) %>
          <% else %>
              <span class="status-red"><%= seconds_to_pretty_time(Time.now - cms_request.deadline) %></span>
          <% end %>
        </td>
      </tr>
    <% end %>

  </tbody>
</table>
<div class="pager_control">
  Showing page <%= form_tag({action: :unfinished_translation_jobs}, {method: 'GET'}) %>
  <%= select_tag( :page, options_for_select(@list_of_pages, @cms_requests.number), {onchange: "submit()"}) %>
  <%= link_to("Prev", url_for(action: :unfinished_translation_jobs, page: @cms_requests.prev.number)) if @cms_requests.prev? %>
  <%= link_to("Next", url_for(action: :unfinished_translation_jobs, page: @cms_requests.next.number)) if @cms_requests.next? %>
  </form>
</div>

app/views/supporter/unstarted_auto_assignment_jobs.html.erb
<h1 id="mainheading">Unstarted Auto Assignment Jobs</h1>

<table width="100%" cellspacing="0" cellpadding="3" class="stats">
  <tbody>
  <tr class="headerrow">
    <th>Job ID</th>
    <th>Translator</th>
    <th>Hours since assignment</th>
  </tr>
  <% @grouped_cms_requests.each do |id, items| %>
      <% cms_request  = items.first %>
      <% contracts = cms_request.website_translation_offer.accepted_website_translation_contracts.includes(:translator) %>
      <% row_class = cycle('tr-odd', 'tr-even') %>
      <tr class="<%= row_class %>">
        <td rowspan="<%= items.size %>">
          <%= link_to(cms_request.id, {controller: 'cms_requests', action: 'show', website_id: cms_request.website_id, id: cms_request.id}, target: '_blank') %>
        </td>
        <% items.each do |item| %>
          <% wtc = contracts.where(id: item.wtc_id).first %>
          <% wto = wtc.website_translation_offer %>
          <% translator = wtc.translator %>
          <td>
            <% if translator %>
            <%= link_to(translator.nickname, user_path(translator), target: '_blank') %>
            <% end %>
            |
            <%= link_to('chat',
                        website_website_translation_offer_website_translation_contract_path(wto.website, wto, wtc),
                        target: '_blank'
            )%>
          </td>
          <td>
            <%= auto_assignment_time_elapsed(item.assigned_at) rescue nil %>
          </td>
          <% if items.size > 1 %>
            </tr>
            <tr class="<%= row_class %>">
          <% end %>
        <% end %>
      </tr>
  <% end %>

  </tbody>
</table>

app/views/supporter/web_messages.html.erb
<%= render(:partial=>'/web_messages/web_messages_list', :object=>@web_messages) %>

app/views/supporter/website_translation_offers.html.erb
<% if @offers.length > 0 %>
	<%= infotab_header(['Created', 'Offer', 'Language', 'URL', 'Kind', 'Client', 'Translators']) %>
  <% @offers.each do |website_translation_offer| %>
    <%= render(:partial=>'website_translation_offer', :locals=>{website_translation_offer: website_translation_offer} ) %>
  <% end %>
	</table>
<% end %>