config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  # mount Browserlog::Engine => '/logs'

  resources :vouchers

  resources :downloads do
    collection do
      get :get
    end

    member do
      get :show_recent
    end
  end

  resources :shortcodes do
    member do
      put :toggle_enabled
    end
  end

  resources :money_transactions
  resources :destinations do
    collection do
      get :go
    end

    member do
      get :visits
    end
  end

  resources :help_topics
  resources :help_groups
  resources :help_placements

  resources :feedbacks do
    collection do
      get :list
    end
  end

  resources :error_reports do
    member do
      get :resolution
    end
  end

  resources :users do
    collection do
      get :signup
      post :find_results
      get :list_translation_languages
      post :update_name_and_email
      post :update_translation_language_results
      post :update_display_settings
      get :translation_analytics_welcome
      post :update_password
      get :find
      get :clients
      get :top
      get :my_profile
      get :bilinguals
      get :clients_by_source
      get :translators
      get :request_practice_project
      get :admins
      get :supporters
      post :setup_practice_project
      get :complete_sandbox
      get :remove_compact_display_session
    end

    member do
      post :update_rate
      patch :update_autoassignment
      post :do_verification_deposit
      post :add_from_languages
      get :reset_password
      post :edit_categories
      post :edit_personal_details
      get :validate
      post :invite_to_job
      post :request_external_account_validation
      post :add_to_languages
      get :managed_works
      post :edit_resume
      get :manage_aliases
      post :resend_activation_email
      get :validate_external_account
      post :del_language
      post :update_public
      post :edit_translation_availability
      post :update_tool
      post :edit_affiliate
      post :add_verification_document
      post :add_language_document
      post :toggle_admin_notifications
      post :edit_image
      get :verification
      post :update_tool_others
      post :del_verification_document
      post :del_language_document
      get :resend_confirmation_email
      post :update_bio
      get :manage_works
      get :translator_languages
      post :close_account
      post :edit_language
      post :update_supporter_data
      get :web_messages_list
      post :validate_user_vat
    end

    resources :translators do
      member do
        patch :update_autoassignment
      end
    end

    resources :user_clicks
    resources :vacations

    resources :glossary_terms do
      collection do
        post :csv_export
        post :import
        get :ta_glossary_edit
        get :new_import
        get :new_tmx_import
        post :tmx_import
        post :show_glossary
      end

      member do
        post :edit_translation
        post :locate
      end
    end

    resources :tus do
      collection do
        get :search
      end
    end

    resources :language_managers do
      resources :language_manager_applications do
        member do
          post :update_application_status
          post :create_message
          get :attachment
        end
      end
    end
  end

  resources :bookmarks

  resources :newsletters do
    collection do
      get :feed
      get :sitemap
    end
    member do
      get :plain
      get :count_users
      put :test
    end
  end

  resources :advertisements
  resources :leads do
    collection do
      post :import
    end
  end

  resources :reminders do
    collection do
      get :hide
      get :unhide
      post :delete_selected
    end
  end

  resources :arbitrations do
    collection do
      get :supporter_index
      post :request_cancel_bid
      post :create_cancel_bid_arbitration
      get :pending
      get :summary
    end

    member do
      post :assign_to_supporter
      post :edit_ruling
      post :ask_for_supporter
      post :edit_offer
      post :close
      post :create_message
      post :delete_offer
      post :accept_offer
    end
  end

  resources :projects do
    collection do
      get :lookup_by_private_key
      get :new_sisulizer
      get :searcher
      get :continue_sisulizer
      post :create_sisulizer
      get :summary
    end

    member do
      get :can_create_new_revisions
    end

    resources :support_files

    resources :revisions do
      collection do
        post :lookup_by_private_key
      end

      member do
        post :transfer_payment_for_translation
        post :edit_name
        post :pay_bids_with_paypal
        post :edit_categories
        get :invite_translator
        post :edit_conditions
        post :pay_bids_with_transfer
        get :support_file
        post :edit_languages
        post :add_required_amount_for_auto_accept
        post :reuse_translators
        post :edit_source_language
        get :select_private_translators
        post :edit_file_upload
        post :edit_project_description
        post :review_payment_for_private_translators
        post :edit_description
        post :edit_release_status
        post :update_supporter_data
        get :support_files
      end

      resources :versions do
        member do
          post :duplicate_complete
        end
      end

      resources :chats do
        collection do
          post :send_broadcast
        end

        member do
          post :check_invoice_status
          post :delete_bid
          post :finalize_review
          post :transfer_bid_payment
          post :reopen
          post :refuse_bid
          post :enable_review
          post :finalize_bids
          post :cancel_bid
          post :pay_for_review
          put :update_bid
          post :declare_done
          post :create_message
          post :cancel_review
          post :edit_bid
          post :open_bid_to_edit
          post :accept_bid
          get :attachment
          post :set_access
          post :save_bid
          post :review_complete
          post :finalize_bid
        end

        resources :bids do
          collection do
            post :unset_all_bids
          end

          member do
            post :unset_bid
          end
        end
      end
    end
  end

  resources :websites do
    collection do
      post :ts_quote
      get :new_user
      get :cms_requests
      get :searcher
      get :translators
      post :create_by_cms
      get :validate_affiliate
    end

    member do
      get :search_cms
      get :request_transfer_account
      get :custom_text
      post :close_all
      post :transfer_account
      get :flush_requests
      get :explain
      get :create_language_pair
      get :quote
      post :add_counts
      get :web_messages_for_pickup
      post :reuse_translators
      get :get
      post :create_explanation
      post :store
      get :translator_chat
      post :swap_translators
      post :ack_message_pickup
      post :create_message
      get :new_ticket
      get :language_pair
      post :edit_tm_use
      post :update_by_cms
      post :migrate
      post :edit_description
      post :update_supporter_data
      post :create_ticket
      get :links
      post :confirm_resignation
      post :confirmed_resignation
      get :cancel_resignation
      post :reveal_wp_credentials
      get :all_comm_errors
    end

    resources :shortcodes do
      member do
        put :toggle_enabled
      end
    end

    resources :translation_snapshots do
      collection do
        post :create_by_cms
      end
    end

    resources :website_translation_offers do
      collection do
        get :enter_password
        get :load_or_create_from_ta
      end

      member do
        get :review
        get :report
        post :cancel_invitations
        get :enter_details
        post :update_details
        post :resend_notifications
        post :update_site_status
        get :new_invitation
        get :auto_setup
        post :edit_description
        post :create_invitation
        get :resign_from_website
      end

      resources :website_translation_contracts do
        member do
          post :update_application_status
          post :create_message
          get :attachment
        end
      end
    end

    match '/websites/:website_id/website_translation_contracts/send_broadcast' => 'website_translation_contracts#send_broadcast', :as => :website_translation_contracts_broadcast, via: [:post]

    resources :cms_requests do
      collection do
        get :report
        get :count_requests_to_pickup
        get :cms_id
        post :update_cms_id
        post :multiple_retry
        post :cancel_multiple_translations
      end

      member do
        post :retry
        get :cms_upload
        get :get_html_output
        post :notify_tas_done
        post :store_output
        post :enable_review
        post :report_error
        post :close_all_errors
        get :chat
        post :reset
        get :cms_download
        post :cancel_translation
        post :resend
        post :redo
        post :update_status
        post :debug_complete
        post :create_message
        get :xliff
        post :update_permlink
        post :release
        post :deliver
        post :assign_to_me
        post :notify_cms_delivery
        get :download
        post :update_languages
        post :toggle_tmt_config
        post :toggle_force_ta
      end

      resources :comm_errors
    end

    resources :cms_terms do
      resources :cms_term_translations
    end
  end

  match 'wpml-websites/:id.:format' => 'websites#show', :via => :get

  resources :web_messages do
    collection do
      get :review_index
      get :searcher
      get :fetch_next
      post :pre_create
      post :select_to_languages
    end

    member do
      get :review
      get :translation

app/models/glossary_term.rb
class GlossaryTerm < ApplicationRecord
  belongs_to :client
  belongs_to :language
  has_many :glossary_translations, dependent: :destroy

  validates :txt, :language_id, presence: true
  validates :txt, length: { maximum: COMMON_FIELD }
  validates :description, length: { maximum: COMMON_FIELD }

  COMMON_WORDS = ['the', 'of', 'and', 'a', 'to', 'in', 'is', 'you', 'that', 'it', 'he', 'was', 'for', 'on', 'are', 'as', 'with', 'his', 'they', 'i', 'at', 'be',
                  'this', 'have', 'from', 'or', 'one', 'had', 'by', 'word', 'but', 'not', 'what', 'all', 'were', 'we', 'when', 'your', 'can', 'said', 'there', 'use', 'an', 'each',
                  'which', 'she', 'do', 'how', 'their', 'if', 'will', 'up', 'other', 'about', 'out', 'many', 'then', 'them', 'these', 'so', 'some', 'her', 'would', 'make', 'like', 'him',
                  'into', 'time', 'has', 'look', 'two', 'more', 'write', 'go', 'see', 'number', 'no', 'way', 'could', 'people', 'my', 'than', 'first', 'water', 'been', 'call', 'who',
                  'oil', 'its', 'now', 'find', 'long', 'down', 'day', 'did', 'get', 'come', 'made', 'may', 'part', 'over', 'new', 'sound', 'take', 'only', 'little', 'work', 'know',
                  'place', 'year', 'live', 'me', 'back', 'give', 'most', 'very', 'after', 'thing', 'our', 'just', 'name', 'good', 'sentence', 'man', 'think', 'say', 'great', 'where',
                  'help', 'through', 'much', 'before', 'line', 'right', 'too', 'mean', 'old', 'any', 'same', 'tell', 'boy', 'follow', 'came', 'want', 'show', 'also', 'around', 'form',
                  'three', 'small', 'set', 'put', 'end', 'does', 'another', 'well', 'large', 'must', 'big', 'even', 'such', 'because', 'turn', 'here', 'why', 'ask', 'went', 'men',
                  'read', 'need', 'land', 'different', 'home', 'us', 'move', 'try', 'kind', 'hand', 'picture', 'again', 'change', 'off', 'play', 'spell', 'air', 'away', 'animal',
                  'house', 'point', 'page', 'letter', 'mother', 'answer', 'found', 'study', 'still', 'learn', 'should', 'America', 'world', 'high', 'every', 'near', 'add', 'food',
                  'between', 'own', 'below', 'country', 'plant', 'last', 'school', 'father', 'keep', 'tree', 'never', 'start', 'city', 'earth', 'eye', 'light', 'thought', 'head',
                  'under', 'story', 'saw', 'left', "don't", 'few', 'while', 'along', 'might', 'close', 'something', 'seem', 'next', 'hard', 'open', 'example', 'begin', 'life',
                  'always', 'those', 'both', 'paper', 'together', 'got', 'group', 'often', 'run', 'important', 'until', 'children', 'side', 'feet', 'car', 'mile', 'night', 'walk',
                  'white', 'sea', 'began', 'grow', 'took', 'river', 'four', 'carry', 'state', 'once', 'book', 'hear', 'stop', 'without', 'second', 'later', 'miss', 'idea', 'enough',
                  'eat', 'face', 'watch', 'far', 'indian', 'really', 'almost', 'let', 'above', 'girl', 'sometimes', 'mountain', 'cut', 'young', 'talk', 'soon', 'list', 'song', 'being',
                  'leave', 'family', "it's", 's'].freeze

  PUNCTUATION = ['.', ',', '"', "'", ':', ';', '(', ')', '[', ']', '{', '}'].freeze

  def self.split_with_punctuation(txt)
    t = txt
    PUNCTUATION.each { |p| t = t.gsub(p, ' ') }
    t.split
  end

  def self.find_frequent_words(txt)
    t = txt
    PUNCTUATION.each { |p| t = t.gsub(p, ' ') }
    words = t.split
    hist = {}
    count = 0
    words.each do |w|
      wl = w.downcase
      next unless (wl.length > 2) && !COMMON_WORDS.include?(wl)
      if !hist.key?(wl)
        hist[wl] = 1
      else
        hist[wl] += 1
      end
      count += 1
    end

    to_sort = []
    hist.each { |k, v| to_sort << [v, k] }

    res = []
    counted = 0

    stop_count = (count / 7).to_i

    to_sort.sort.reverse.each do |item|
      res << item[1]
      counted += item[0]
      break if counted >= stop_count
    end

    res

  end

  def self.webta_create(params, cms_request)
    return ApiError.new(400, 'Glossary term can not be blank', 'INVALID DATA').error if params[:term].blank?
    return ApiError.new(400, 'Description can not be blank', 'INVALID DATA').error if params[:description].blank?
    return ApiError.new(400, 'Translated text can not be blank', 'INVALID DATA').error if params[:translated_text].blank?
    target_language = cms_request.cms_target_language.language

    glossary_params = {
      client_id: cms_request.website.client_id,
      txt: params[:term],
      description: params[:description],
      language_id: cms_request.language_id
    }
    glossary = GlossaryTerm.new(glossary_params)
    glossary.glossary_translations.new(txt: params[:translated_text], language_id: target_language.id)
    glossary.save!

    glossary.to_json(target_language)
  rescue => e
    return ApiError.new(400, e.message, 'UNEXPECTED ERROR').error
  end

  def self.webta_update(params, cms_request, user)
    glossary_term = GlossaryTerm.find_by_id(params[:id])
    return ApiError.new(404, 'Glossary term not found', 'NOT FOUND').error unless glossary_term.present?
    return ApiError.new(403, 'Can not update this term', 'NOT ALLOWED').error unless glossary_term.client_id == cms_request.website.client_id
    glossary_term.update_attributes!(description: params[:description]) if params[:description].present?
    if params[:translation].present? && params[:target_language_id]
      glossary_translation = glossary_term.glossary_translations.where(language_id: params[:target_language_id]).last
      if glossary_translation.present?
        glossary_translation.update_attributes!(txt: params[:translation], last_editor_id: user.id)
      else
        GlossaryTranslation.new(
          glossary_term_id: glossary_term.id,
          language_id: params[:target_language_id],
          txt: params[:translation],
          creator_id: user.id,
          last_editor_id: user.id
        ).save!
      end
    end
    return { code: 200, status: 'OK', message: 'Glossary updated' }
  rescue => e
    return ApiError.new(400, e.message, 'UNEXPECTED ERROR').error
  end

  def to_json(target_language)
    {
      id: self.id,
      term: self.txt,
      description: self.description,
      original_language: self.language.name,
      translated_text: self.glossary_translations.where(language: target_language).first.txt,
      translation_language: target_language.name
    }
  end

end

app/helpers/glossary_terms_helper.rb
module GlossaryTermsHelper
end

app/views/glossary_terms/_glossary_panel.html.erb
<% if @glossary_client && @glossary_languages && (@glossary_languages.length > 0) %>
    <div <% unless session[:ta_glossary_edit] %>style="padding: 1em; background-color: #D0D0F0;"<% end %> >

        <% unless session[:ta_glossary_edit] %>
            <% if @user == @glossary_client %>
                Your glossary from <strong><%= @glossary_orig_language.name %></strong> to <strong><%= (@glossary_languages.collect { |l| l.name }).join(', ') %></strong>.
            <% else %>
                Glossary for <strong><%= @glossary_client.full_name %></strong> from <strong><%= @glossary_orig_language.name %></strong> to <strong><%= (@glossary_languages.collect { |l| l.name }).join(', ') %></strong>.
            <% end %>
            <%= form_tag({:controller=>:glossary_terms, :action=>:show_glossary, :user_id=>@glossary_client.id}, :remote => true) do %>
              <% label = (session[:show_glossary] ? 'Close glossary' : 'Edit glossary') %>
              <%= submit_tag(label, data: { disable_with: label }) %>
            <% end %>
        <% end %>

        <% if session[:ta_glossary_edit] || session[:show_glossary] %>
            <% if !session[:ta_glossary_edit] %>
                <div style="margin: 0.5em; padding: 0.5em; max-height: 15em; overflow:auto;">
            <% end %>

            <%= glossary_edit_list %>

            <% if !session[:ta_glossary_edit] %>
                </div>
            <% end %>

            <br />
            <div id="new_glossary">
                <%= render(:partial=>'/glossary_terms/glossary_term') %>
            </div>

            <% if !session[:ta_glossary_edit] %>
                <a href="#mainheading">Back to top</a>
            <% end %>

        <% end %>

	</div>
	<br />
<% end %>

app/views/glossary_terms/_glossary_term.html.erb
<% if !@locate && @glossary_term %>
	<h3><%= @header %></h3>
    <%= form_for(:glossary_term, :url=>{:action=>@action}, :method=>@method, :remote => true) do |f| %>
		<p>Text: <%= f.text_field(:txt, maxlength: COMMON_FIELD, size: COMMON_FIELD_SIZE) %><br />
		<span class="comment">Enter the text that needs special attention</span></p>
		<p>Description: <%= f.text_field(:description, :size=>80, maxlength: COMMON_FIELD) %><br />
		<span class="comment">Describe the context of the text and what it is used for</span></p>
		<p>Language: <%= f.select(:language_id, @languages) %><br />
		<span class="comment">The language of the text</span></p>
		<%= submit_tag('Save', data: { disable_with: 'Save' }) %>
	<% end %>
    <%= form_tag({ :action=>:new, :req=>'hide'}, :method => :get, :remote => true) do %>
		<%= submit_tag 'Cancel', data: { disable_with: 'Cancel' } %>
	<% end %>
	
	<% if !@glossary_term.id.blank? && (@user == @glossary_client) %>
		<br /><br />
        <%= form_tag({ :action => :destroy }, :method => :delete, :remote => true) do %>
			<%= submit_tag('Delete this term', style: 'background-color: #FF8080;', data: { disable_with: 'Delete this term' }) %><br />
			<%= check_box_tag(:confirm_delete) %> I'm sure I want to delete this glossary term.
		<% end %>
	<% end %>
<% else %>
  <p>
      <%= link_to new_user_glossary_term_path(@glossary_client.id), :remote => true do %>
         <%= image_tag "icons/add.png",  :align => "bottom",  :border => "0",  :width => "16",  :height => "16", :alt => "add" %>
          New glossary entry <%= '&raquo;'.html_safe %>
      <% end %>
  </p>
<% end %>

app/views/glossary_terms/_glossary_translation.html.erb
<% if @editing %>
	<%= form_for(:glossary_translation, :url=>{:action=>:edit_translation}, :remote => true) do |f| %>
		<%= f.text_field(:txt, size: COMMON_FIELD_SIZE, :style=>language_dir_css_attribute(@glossary_translation.language), maxlength: COMMON_NOTE) %><br />
		<% if @glossary_translation %><%= hidden_field_tag(:glossary_translation_id, @glossary_translation.id) %><% end %>
		<%= hidden_field_tag(:language_id,@language.id) %>
		<%= f.hidden_field(:language_id) %>
		<%= submit_tag('Save', data: { disable_with: 'Save' }) %>
	<% end %>
	<%= form_tag({ :action=>:edit_translation, :language_id=>@language.id, :glossary_translation_id=>@glossary_translation.id, :req=>'hide' }, :remote => true) do %>
		<%= submit_tag 'Cancel', data: { disable_with: 'Cancel' } %>
	<% end %>
<% elsif @glossary_translation %>
	<%= link_to({:action=>:edit_translation, :user_id=>@glossary_client.id, :id=>@glossary_term.id, :glossary_translation_id=>@glossary_translation.id, :req=>'show'}, :title=>'Edit', :remote => true, method: :post) do %>
    <%= image_tag 'icons/edit.png', width: 16, height: 16, alt: 'edit', align: 'bottom' %>
  <% end %>
  <%= h(@glossary_translation.txt)  %>
<% else %>
	 <%= link_to({:action=>:edit_translation, :user_id=>@glossary_client.id, :id=>@glossary_term.id, :language_id=>@language.id, :req=>'new' }, :remote => true, method: :post) do %>
    <%= image_tag 'icons/add.png', width: 16, height: 16, border: 0, alt: 'add', align: 'bottom' %>
   <% end %>
<% end %>

app/views/glossary_terms/create.js.erb
<% if @warning %>
  alert('<%= @warning.squish %>')
<% else %>
  jQuery('#glossary_edit').html('<%= escape_javascript(render partial: '/glossary_terms/glossary_panel') %>')
  jQuery('#new_glossary').html('<%= escape_javascript(render partial: '/glossary_terms/glossary_term') %>')
<% end %>

app/views/glossary_terms/destroy.js.erb
<% if @warning %>
alert('<%= @warning %>')
<% else %>
jQuery('#glossary_edit').html('<%= escape_javascript(render partial: '/glossary_terms/glossary_panel') %>')
jQuery('#new_glossary').html('<%= escape_javascript(render partial: '/glossary_terms/glossary_term') %>')
<% end %>

app/views/glossary_terms/edit_translation.js.erb
<% if @warning %>
alert('<%= @warning %>')
<% else %>
jQuery('#glossary_translation_<%= @glossary_term.id %>_<%= @language.name %>').html('<%= escape_javascript(render partial: 'glossary_translation') %>')
<% end %>

app/views/glossary_terms/import.html.erb
<% if @problem %>
  <h3>Error Processing file</h3>

  <p><%= @problem %></p>
<% else %>
  
  <p>It worked!</p> 

<% end %>

<p>Created <%= @created %> items, update <%= @updated %>.</p>

<p><%= link_to('Back to list',{:action=>:index}) %></p>

app/views/glossary_terms/index.html.erb
<p>The glossary is where you keep a list of translations for important phrases.</p>
<p>All the translators working on your projects have access to the glossary. When they translate texts that include words from the glossary, they will see the existing translations.</p>
<p>Glossary terms are made of pairs of <b>text</b> and <b>description</b>, allowing you to include the same phrases, used in different contexts.</p>

<% if @user == @glossary_client %>

	<p><%= link_to('Import glossary from spreadsheet', {:action=>'new_import'}) %></p>

	<br /><br />
	<div class="infobox"><h4>Export glossary</h4>
		<%= form_tag(:action=>:csv_export) do %>
			<p>Select source language: <%= select_tag(:language_id, options_for_select(Language.list_major_first)) %></p>
			<%= submit_tag('Export', data: { disable_with: 'Export' }) %>
		<% end %>
	</div>

<% end %>

app/views/glossary_terms/locate.js.erb
jQuery('#glossary_edit').html('<%= escape_javascript(render partial: '/glossary_terms/glossary_panel') %>')
jQuery('html, body').animate({
  scrollTop: jQuery("#glossary_edit").offset().top
}, 2000);

app/views/glossary_terms/new.js.erb
jQuery('#new_glossary').html('<%= escape_javascript(render partial: '/glossary_terms/glossary_term') %>')

app/views/glossary_terms/new_import.html.erb
<p>To populate the glossary table, create a CSV (comma separated file) with the terms, their description and translations.</p>
<h3>Glossary CSV file example</h3>
<p>This example shows a CSV file translating to German and Spanish. The two first columns (<i>term</i>, <i>description</i>) are required. Then, add a column for each language.</p>
<p>Entries that are blank will be ignored.</p>
<table class="glossary_sample">
	<tr><th>Term</th><th>Description</th><th>Spanish</th><th>German</th></tr>
	<tr><td>home</td><td>Place to live</td><td>hogar</td><td>haus</td></tr>
	<tr><td>home</td><td>Link to root of site</td><td>inicio</td><td>start</td></tr>
	<tr><td>link</td><td>Connect to something physical</td><td>conexión</td><td></td></tr>
	<tr><td>link</td><td>Hyperlink in website</td><td>enlace</td><td></td></tr>
</table>
<p>The file that you produce should be saved as Unicode-UTF8, using double quotes around cells and deliminated with commas. This is the above file, viewed with a plain text editor:</p>
<pre>
"Term","Description","Spanish","German"
"home","Place to live","hogar","haus"
"home","Link to root of site","inicio","start"
"link","Connect to something physical","conexión",""
"link","Hyperlink in website","enlace",""
</pre>

<br />
<h3>Upload</h3>
<%= form_tag({:action=>:import}, {:multipart=>true}) do %>
	<p><b>Select the language of the terms you're uploading</b><br />
	<%= select_tag(:language_id, options_for_select(@languages)) %></p>
	<p><b>Select CSV file to upload</b><br />
	<%= file_field_tag('file', :size=>70, data: { disable_with: 'Processing...' }) %></p>
	<p><%= submit_tag('upload', :style=>'padding: 0.5em 1em;', data: { disable_with: 'Please wait' }) %> &nbsp; | &nbsp; <%= link_to('Cancel', {:action=>:index}) %></p>
<% end %>

app/views/glossary_terms/new_tmx_import.html.erb
<%= form_tag({:action=>:tmx_import}, {:multipart=>true}) do %>
	<p><b>Select TMX file to upload</b><br />
	<%= file_field_tag('file', :size=>70, data: { disable_with: 'Processing...' }) %></p>
	<p><%= submit_tag('upload', :style=>'padding: 0.5em 1em;', data: { disable_with: 'Please wait' }) %> &nbsp; | &nbsp; <%= link_to('Cancel', {:action=>:index}) %></p>
<% end %>

app/views/glossary_terms/ta_glossary_edit.html.erb
<div id="glossary_edit"><%= render(:partial=>'/glossary_terms/glossary_panel') %></div>

app/views/glossary_terms/update.js.erb
<% if @warning %>
alert('<%= @warning.squish %>')
<% else %>
jQuery('#glossary_edit').html('<%= escape_javascript(render partial: '/glossary_terms/glossary_panel') %>')
jQuery('#new_glossary').html('<%= escape_javascript(render partial: '/glossary_terms/glossary_term') %>')
<% end %>